apiVersion: v1
kind: Service
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
{{- if eq .Values.service.type "node" }}
  type: NodePort
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    name: http
  - nodePort: 30443
    port: 443
    protocol: TCP
    name: https
  selector:
    app: {{ template "rancher.fullname" . }}
{{- else -}}  
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ template "rancher.fullname" . }}
{{- end -}}
